#!/usr/bin/env bash
#
# author: daniel neemann (@zzzeyez)
#
# displays notifications on macos
# requires `ubersicht` and `imagemagick`

uber="${HOME}/Library/Application Support/Übersicht/widgets/"
image="$uber/xanthia/image.png"
message="$uber/xanthia/message"

exists() {
    type "$1" &> /dev/null ;
}

setup() {
	touch "$message"
}

icon() {
	convert "$1" "$image" &&
	ps cax | grep sicht > /dev/null
	if [ $? -eq 0 ]; then
	osascript -e 'tell application "'$(ps ax | grep sicht | awk '{print $5}' | \
	head -1 | cut -d/ -f3 | cut -d. -f1)'" to refresh widget id "xanthia-image-coffee"'
	fi
}

notify() {
	echo "$1" > "$message" &&
	ps cax | grep sicht > /dev/null
	if [ $? -eq 0 ]; then
		osascript -e 'tell application "'$(ps ax | grep sicht | awk '{print $5}' | \
		head -1 | cut -d/ -f3 | cut -d. -f1)'" to refresh widget id "xanthia-message-coffee"'
	elif exists /usr/local/bin/terminal-notifier
	then
		terminal-notifier -message "$(cat "$message")" -appIcon "$image"
	else
		exit
	fi
}

flags() {
	while getopts m:i: opt; do
		case $opt in
		m) notify "$OPTARG"
		;;
		i) icon "$OPTARG"
		;;
	esac
	done
}

if [ "$#" -gt 1 ]; then
	setup
	flags "$@"
else
	setup
	notify "$@"
fi
