#!/usr/bin/env bash
sed -i '' "s/zzzeyez/$USER/g" "$(dirname "$0")/scss/message.scss"
sassc --style expanded "$(dirname "$0")/scss/message.scss" > "$(dirname "$0")/message.css" &
ps cax | grep bersicht > /dev/null
if [ $? -eq 0 ]; then
	osascript -e 'tell application "Übersicht" to refresh widget id "xanthia-messagestyle-coffee"'
fi
