#!/usr/bin/env bash

cache="xanthia/.cache"
defaults="xanthia/.defaults"

if [[ -d "$cache" ]] ; then
	head -1 "$cache/message"
else
	mkdir "$cache" &&
	cp "$defaults/image.png" "$cache/image.png"
	cp "$defaults/message" "$cache/message"
	sleep 1s &&
	head -1 "$cache/message"
	ubersicht="$(ps ax | grep sicht | awk '{print $5}' | head -1 | cut -d/ -f3 | cut -d. -f1)"
	if [[ "$ubersicht" = "UM-LM^Hbersicht" ]] ; then
		ubersicht="Übersicht"
	fi		
	osascript -e 'tell application "'$ubersicht'" to refresh widget id "xanthia-image-jsx"'
fi
